---

- name: "Create directory for Server"
  file:
    path: ~/server
    state: directory

- name: "Extract files"
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/server


- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "Install dependencies 2"
  shell: |
    cd ~/server
    npm i

- name: "Run Server"
  shell: |
    cd ~/server
    pm2 stop default
    pm2 start npm --start

